language: objective-c
osx_image: xcode7.3
xcode_workspace: ADMozaikCollectionViewLayout.xcworkspace
xcode_scheme: ADMozaikCollectionViewLayout
xcode_sdk: iphonesimulator9.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
cache:
  - bundler
  - cocoapods
install:
    - bundle install
    - bundle exec pod repo update
    - bundle exec pod install
script:
  - xctool -workspace ADMozaikCollectionViewLayout.xcworkspace -scheme ADMozaikCollectionViewLayout build test -sdk iphonesimulator -destination="platform=iOS Simulator,name=iPhone 6,OS=9.3" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
