//
//  ADMozaikLayoutAttributes.swift
//  ADMozaikCollectionViewLayout
//
//  Created by Anton Domashnev on 14/06/16.
//  Copyright © 2016 Anton Domashnev. All rights reserved.
//

import Foundation

/// Enum with the all possible errors generated by `ADMozaikLayoutAttributes`
///
/// - notAllSectionsPrepared: missing information for collectionView section
enum ADMozaikLayoutAttributesError: Error {
    case notAllSectionsPrepared
}

class ADMozaikLayoutAttributes {
    
    /// Array of `UICollectionViewLayoutAttributes`
    fileprivate(set) var layoutAttributesArray: [UICollectionViewLayoutAttributes] = []
    
    /// Array of unified rects of each 20 layout attributes
    fileprivate(set) var unionRectsArray: [CGRect] = []
    
    /// Default number of attributes in one union
    fileprivate let ADMozaikLayoutUnionSize: Int = 20
    
    /// ADMozaikLayout cache reference
    fileprivate let layoutCache: ADMozaikLayoutCache
    
    init(layoutCache: ADMozaikLayoutCache, layoutMatrixes: [ADMozaikLayoutSectionMatrix], layoutGeometries: [ADMozaikLayoutSectionGeometry]) throws {
        self.layoutCache = layoutCache
        self.layoutAttributesArray = try self.buildLayoutAttributesForLayoutGeometries(layoutGeometries, withLayoutMatrixes: layoutMatrixes)
        self.unionRectsArray = self.buildUnionRectsFromLayoutAttributes(self.layoutAttributesArray)
    }
    
    //MARK: - Interface
    
    func layoutAttributesForItem(at indexPath: IndexPath) -> UICollectionViewLayoutAttributes? {
        let attribute = self.layoutAttributesArray[indexPath.item]
        return attribute
    }
    
    func layoutAttributesForElementsInRect(_ rect: CGRect) -> [UICollectionViewLayoutAttributes]? {
        var resultAttributes: [UICollectionViewLayoutAttributes] = []
        let unionRectsCount = self.unionRectsArray.count
        var begin = 0
        var end = unionRectsCount
        
        for unionRectIndex in (0..<unionRectsCount) {
            if !rect.intersects(self.unionRectsArray[unionRectIndex]) {
                continue
            }
            begin = unionRectIndex * ADMozaikLayoutUnionSize
            break
        }
        
        for unionRectIndex in (0..<unionRectsCount).reversed() {
            if !rect.intersects(self.unionRectsArray[unionRectIndex]) {
                continue
            }
            end = min((unionRectIndex + 1) * ADMozaikLayoutUnionSize, self.layoutAttributesArray.count)
            break
        }
        
        for i in begin..<end {
            let attributes = self.layoutAttributesArray[i]
            if rect.intersects(attributes.frame) {
                resultAttributes.append(attributes)
            }
        }
        
        return resultAttributes
    }
    
    //MARK: - Helper
    
    fileprivate func buildLayoutAttributesForLayoutGeometries(_ layoutGeometries: [ADMozaikLayoutSectionGeometry], withLayoutMatrixes layoutMatrixes: [ADMozaikLayoutSectionMatrix]) throws -> [UICollectionViewLayoutAttributes] {
        let numberOfSections = layoutCache.numberOfSections()
        guard layoutGeometries.count == numberOfSections && layoutMatrixes.count == numberOfSections else {
            throw ADMozaikLayoutAttributesError.notAllSectionsPrepared
        }
        var allAttributes: [UICollectionViewLayoutAttributes] = []
        var layoutSectionGeometryOffsetY: CGFloat = 0
        for section in 0..<numberOfSections {
            let itemsCount = layoutCache.numberOfItemsInSection(section)
            let layoutGeometry = layoutGeometries[section]
            let layoutMatrix = layoutMatrixes[section]
            
            if let attributes = buildLayoutAttributesForSupplementaryView(of: UICollectionElementKindSectionHeader, in: section, geometry: layoutGeometry, additionalOffsetY: layoutSectionGeometryOffsetY) {
                allAttributes.append(attributes)
            }
            
            for item in 0..<itemsCount {
                let indexPath = IndexPath(item: item, section: section)
                do {
                    let attributes = try buildLayoutAttributesForItem(at: indexPath, geometry: layoutGeometry, matrix: layoutMatrix, additionalOffsetY: layoutSectionGeometryOffsetY)
                    allAttributes.append(attributes)
                }
                catch let error as CustomStringConvertible {
                    fatalError(error.description)
                }
            }
            
            if let attributes = buildLayoutAttributesForSupplementaryView(of: UICollectionElementKindSectionFooter, in: section, geometry: layoutGeometry, additionalOffsetY: layoutSectionGeometryOffsetY) {
                allAttributes.append(attributes)
            }
            
            layoutSectionGeometryOffsetY += layoutGeometry.contentHeight
        }
        return allAttributes
    }
    
    fileprivate func buildLayoutAttributesForSupplementaryView(of kind: String, in section: ADMozaikLayoutSection, geometry: ADMozaikLayoutSectionGeometry, additionalOffsetY: CGFloat) -> UICollectionViewLayoutAttributes? {
        guard let frame = geometry.frameForSupplementaryView(of: kind) else {
            return nil
        }
        let indexPath = IndexPath(item: 0, section: section)
        let attributes = UICollectionViewLayoutAttributes(forSupplementaryViewOfKind: kind, with: indexPath)
        attributes.frame = CGRect(x: frame.origin.x, y: frame.origin.y + additionalOffsetY, width: frame.width, height: frame.height)
        geometry.registerElement(with: frame)
        return attributes
    }
    
    fileprivate func buildLayoutAttributesForItem(at indexPath: IndexPath, geometry: ADMozaikLayoutSectionGeometry, matrix: ADMozaikLayoutSectionMatrix, additionalOffsetY: CGFloat) throws -> UICollectionViewLayoutAttributes {
        let itemSize = layoutCache.mozaikSizeForItem(atIndexPath: indexPath)
        let itemPosition = try matrix.positionForItem(of: itemSize)
        let itemGeometryFrame = geometry.frameForItem(withMozaikSize: itemSize, at: itemPosition)
        let attributes = UICollectionViewLayoutAttributes(forCellWith: indexPath)
        attributes.frame = CGRect(x: itemGeometryFrame.origin.x, y: itemGeometryFrame.origin.y + additionalOffsetY, width: itemGeometryFrame.width, height: itemGeometryFrame.height)
        geometry.registerElement(with: itemGeometryFrame)
        try matrix.addItem(of: itemSize, at: itemPosition)
        return attributes
        
    }
    
    fileprivate func buildUnionRectsFromLayoutAttributes(_ attributes: [UICollectionViewLayoutAttributes]) -> [CGRect] {
        var index = 0
        var unionRectsArray: [CGRect] = []
        let itemsCount = attributes.count
        while index < itemsCount {
            let frame1 = attributes[index].frame
            index = min(index + ADMozaikLayoutUnionSize, itemsCount) - 1
            let frame2 = attributes[index].frame
            unionRectsArray.append(frame1.union(frame2))
            index += 1
        }
        return unionRectsArray
    }
    
}
